baseURL = 'https://cloudgrunt.com/'
languageCode = 'en-us'
title = 'Cloud Grunt Blog'
theme = 'ananke'

[params]
 site_logo = "/shane2.png"
  show_reading_time = true

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 50

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 50

[[menu.main]]
  name = "Resources"
  url = "/awsresources/"
  weight = 50
  
[[params.ananke_socials]]
name = "Linkedin"
url = "https://www.linkedin.com/in/shane-garnetti/"
